server:
  port: ${PORT:8080}
  #이거 덕분에 mustache 한글 됨.
  servlet:
    encoding:
      force-response: true
      charset: UTF-8
      enabled: true
  forward-headers-strategy: native

jwt:
  access_token_expiration_time: 900 #15분초
  refresh_token_expiration_time: 604800
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa

management:
  endpoints:
    web:
      exposure:
        include: "prometheus,httptrace,metrics"
  metrics:
    export:
      prometheus:
        enabled: true
  tracing:
    sampling:
      probability: 1.0  # 100% 요청 추적

spring:
  profiles:
    active: local
  mustache:
    charset: UTF-8
  mvc:
    static-path-pattern: "/**" #모든 정적 자원 서빙 가능
    view:
      encoding: UTF-8
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

tmap-api-key: ${TMAP_API_KEY}