server:
  compression:
    enabled: false # Content-Length mismatch 문제 방지

logging:
  level:
    org.hibernate.SQL: DEBUG

spring:
  main:
    lazy-initialization: true # 시작 속도 최적화

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver # 아래 url에 DB 이름 주의 (현재 transsys)
    url: jdbc:mysql://${MYSQL_HOST}.mysql.database.azure.com:3306/transsys?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  data:
    redis:
      host: ${REDIS_HOST} # password: <Azure Redis 접속 키>
      port: 6379
      password: ${REDIS_PASSWORD}
      ssl:
        enabled: false

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect

chat-bot:
  api:
    host: ${CHATBOT_HOST}

stock:
  api:
    host: ${STOCK_HOST}

map:
  api:
    host: ${MAP_HOST}

inspection:
  api:
    host: ${INSPECTION_HOST}