# 쿠버네티스 Service: Pod에 안정적으로 접근할 수 있게 해주는 리소스
apiVersion: v1
kind: Service
metadata:
  name: spring-service             # 서비스 이름 (내부 DNS로 사용됨: spring-service)
spec:
  type: ClusterIP                  # 기본 서비스 타입 (클러스터 내부에서만 접근 가능)
  selector:
    app: spring-app                # 어떤 Pod을 대상으로 할지 지정
  ports:
    - port: 80                     # 서비스가 노출하는 포트
      targetPort: 8080            # Pod의 컨테이너 포트
