name: Spring CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. 깃헙 레포지토리 체크아웃
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. JDK 설정 (Amazon Corretto 21)
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 21

      # 3. Gradle 캐시 설정
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      # 4. Gradle로 프로젝트 빌드 (테스트 생략 가능)
      - name: Build with Gradle (skip tests)
        run: ./gradlew build -x test

      # 5. DockerHub 로그인
      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 6. Docker Buildx 설정
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 7. Docker 이미지 빌드 및 푸시
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: kosonkh7/sopo-spring:latest
